# Generated by Django 3.0.5 on 2020-04-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='developer',
            name='last_name',
            field=models.CharField(default='yoni', max_length=100),
            preserve_default=False,
        ),
    ]
